#!/usr/bin/env python3

from charmhelpers.core import unitdata

kv = unitdata.kv()
if kv.get('grafana.admin_password'):
    print('Admin password: {}'.format(kv.get('grafana.admin_password')))
else:
    print('ERROR! Unable to retrieve password. Was it set using config option?')
